on:
  push:
    branches:
      - main
      - 'feat/**'
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "aaa"
          sleep 3
          echo "bbb"
          sleep 3
          echo "ccc"
          sleep 3
          echo "ddd"
          sleep 3
          echo "eee"
          sleep 3
          echo "end"
