on:
  push:
    branches:
      - main
      - 'feat/**'
  pull_request:
    types:
      - opened
      # - synchronize
      # - reopened
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "aaa"
          sleep 3
          echo "bbb"
      - name: step2
        run: |
          sleep 3
          echo "ccc"
          sleep 3
          echo "ddd"
  check2:
    runs-on: ubuntu-latest
    steps:
      - name: step3
        run: |
          sleep 3
          echo "eee"
          sleep 3
          echo "end"
